/**
 * Client ID Generator Service
 * 
 * Generates unique, sequential clientIds for client records
 * Format: C000001, C000002, C000003, etc.
 * 
 * This service ensures:
 * - Server-side generation only (never client-provided)
 * - Sequential numbering for easy reference
 * - Bootstrap-safe (works when database is empty)
 * - Transactional support (works within MongoDB sessions)
 * - Immutability (clientId cannot be changed after creation)
 * - Race-condition safety via transaction isolation
 * 
 * IMPORTANT: No Counter collection is used - IDs are generated by querying
 * the latest document within the same transaction session.
 */

const Client = require('../models/Client.model');

/**
 * Generate the next available clientId within a transaction
 * Queries the latest client and increments, bootstrap-safe for empty collections
 * 
 * @param {string} firmId - Firm ID for tenant scoping (required for firm-isolated IDs)
 * @param {object} session - MongoDB session for transactional reads (required for atomicity)
 * @returns {Promise<string>} Next clientId in format C000001
 */
const generateNextClientId = async (firmId, session = null) => {
  if (!firmId) {
    throw new Error('firmId is required for client ID generation');
  }
  try {
    // Query the latest client within the transaction session
    // Sort by createdAt descending to get the most recent
    // Scope by firmId to ensure firm-isolated ID generation
    const queryOptions = session ? { session } : {};
    const lastClient = await Client
      .findOne({ firmId }, {}, queryOptions)
      .sort({ createdAt: -1 });
    
    // Bootstrap case: no clients exist yet
    if (!lastClient || !lastClient.clientId) {
      return 'C000001';
    }
    
    // Extract the numeric portion from the last clientId (e.g., C000001 -> 1)
    const lastNumber = parseInt(lastClient.clientId.slice(1), 10);
    
    // Increment and format with leading zeros (6 digits)
    const nextNumber = lastNumber + 1;
    const clientId = `C${String(nextNumber).padStart(6, '0')}`;
    
    return clientId;
  } catch (error) {
    console.error('[Client ID Generator] Error generating clientId:', error);
    throw new Error('Failed to generate clientId during firm provisioning');
  }
};

/**
 * Validate clientId format
 * @param {string} clientId - clientId to validate
 * @returns {boolean} True if valid format
 */
const validateClientIdFormat = (clientId) => {
  if (!clientId || typeof clientId !== 'string') {
    return false;
  }
  
  // Must match format: C followed by 6 digits
  return /^C\d{6}$/.test(clientId);
};

/**
 * Check if clientId already exists
 * @param {string} clientId - clientId to check
 * @returns {Promise<boolean>} True if clientId exists
 */
const clientIdExists = async (clientId) => {
  try {
    const client = await Client.findOne({ clientId }).lean();
    return !!client;
  } catch (error) {
    console.error('[Client ID Generator] Error checking clientId existence:', error);
    throw new Error('Failed to check clientId existence');
  }
};

module.exports = {
  generateNextClientId,
  validateClientIdFormat,
  clientIdExists,
};
