/**
 * xID Generator Service
 * 
 * Generates unique, sequential xIDs for user accounts
 * Format: X000001, X000002, X000003, etc.
 * 
 * This service ensures:
 * - Server-side generation only (never client-provided)
 * - Sequential numbering for easy reference
 * - Bootstrap-safe (works when database is empty)
 * - Transactional support (works within MongoDB sessions)
 * - Immutability (xID cannot be changed after creation)
 * - Race-condition safety via transaction isolation
 * 
 * IMPORTANT: No Counter collection is used - IDs are generated by querying
 * the latest document within the same transaction session.
 */

const User = require('../models/User.model');

/**
 * Generate the next available xID within a transaction
 * Queries the latest user and increments, bootstrap-safe for empty collections
 * 
 * @param {string} firmId - Firm ID for tenant scoping (required for firm-isolated IDs)
 * @param {object} session - MongoDB session for transactional reads (required for atomicity)
 * @returns {Promise<string>} Next xID in format X000001
 */
const generateNextXID = async (firmId, session = null) => {
  if (!firmId) {
    throw new Error('firmId is required for xID generation');
  }
  try {
    // Query the latest user within the transaction session
    // Sort by createdAt descending to get the most recent
    // Scope by firmId to ensure firm-isolated ID generation
    const queryOptions = session ? { session } : {};
    const lastUser = await User
      .findOne({ firmId }, {}, queryOptions)
      .sort({ createdAt: -1 });
    
    // Bootstrap case: no users exist yet
    if (!lastUser || !lastUser.xID) {
      console.log(`[xID Generator] Bootstrap: Generated first xID: X000001 for firm: ${firmId}`);
      return 'X000001';
    }
    
    // Extract the numeric portion from the last xID (e.g., X000001 -> 1)
    const lastNumber = parseInt(lastUser.xID.slice(1), 10);
    
    // Increment and format with leading zeros (6 digits)
    const nextNumber = lastNumber + 1;
    const xID = `X${String(nextNumber).padStart(6, '0')}`;
    
    console.log(`[xID Generator] Generated xID: ${xID} for firm: ${firmId}`);
    
    return xID;
  } catch (error) {
    console.error('[xID Generator] Error generating xID:', error);
    throw new Error('Failed to generate xID during firm provisioning');
  }
};

/**
 * Validate xID format
 * @param {string} xID - xID to validate
 * @returns {boolean} True if valid format
 */
const validateXIDFormat = (xID) => {
  if (!xID || typeof xID !== 'string') {
    return false;
  }
  
  // Must match format: X followed by 6 digits
  return /^X\d{6}$/.test(xID);
};

/**
 * Check if xID already exists
 * @param {string} xID - xID to check
 * @returns {Promise<boolean>} True if xID exists
 */
const xIDExists = async (xID) => {
  try {
    const user = await User.findOne({ xID: xID.toUpperCase() }).lean();
    return !!user;
  } catch (error) {
    console.error('[xID Generator] Error checking xID existence:', error);
    throw new Error('Failed to check xID existence');
  }
};

module.exports = {
  generateNextXID,
  validateXIDFormat,
  xIDExists,
};
